# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='caption',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
